// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkqLzKXjjUC1h3fYOXSeYQw1dS8EhzoQs',
    appId: '1:438087113325:web:e8faa0c255939548057d64',
    messagingSenderId: '438087113325',
    projectId: 'anmol-vachan-a674b',
    authDomain: 'anmol-vachan-a674b.firebaseapp.com',
    storageBucket: 'anmol-vachan-a674b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBioTeZDQUZLL1596Jug6WKIcRf5jK5UDY',
    appId: '1:438087113325:android:a9c5f46b5969ec28057d64',
    messagingSenderId: '438087113325',
    projectId: 'anmol-vachan-a674b',
    storageBucket: 'anmol-vachan-a674b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPdLe53xuasn_CznHgH92RzhIEB_IOng4',
    appId: '1:438087113325:ios:ce852ccdd5ba21d7057d64',
    messagingSenderId: '438087113325',
    projectId: 'anmol-vachan-a674b',
    storageBucket: 'anmol-vachan-a674b.appspot.com',
    iosClientId: '438087113325-psv4hkt9rrlck6ep5lgcii68m5t49i9d.apps.googleusercontent.com',
    iosBundleId: 'com.dhurva.anmolVachan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPdLe53xuasn_CznHgH92RzhIEB_IOng4',
    appId: '1:438087113325:ios:ce852ccdd5ba21d7057d64',
    messagingSenderId: '438087113325',
    projectId: 'anmol-vachan-a674b',
    storageBucket: 'anmol-vachan-a674b.appspot.com',
    iosClientId: '438087113325-psv4hkt9rrlck6ep5lgcii68m5t49i9d.apps.googleusercontent.com',
    iosBundleId: 'com.dhurva.anmolVachan',
  );
}
